language: python
python:
  - "2.7"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7" 
  - "3.8"   
# command to install dependencies
install:
  - pip install -r requirements.txt
  # - pip install coveralls
# os:
#   - linux
#   - osx
# safelist
branches:
  only:
  - master
  # - develop
# command to run tests
script: python  IsoCon pipeline -fl_reads test/data/simulated_pacbio_reads_n_200.fa -outfolder test/out/ 
# after_success:
#  - coveralls